/// User domain models.
///
/// Contains **only** plain data structures used across the auth-lib.
/// - Parsing / validation logic → [`crate::utils`]
/// - Persistence logic         → [`crate::storage::user_repo`]
/// - Business logic            → [`crate::auth::service`]

// ── Persisted entity ──────────────────────────────────────────────────────────

/// A fully hydrated user row as returned from the database.
///
/// Field names and types map 1-to-1 to the `users` table in
/// `src/model/migrations/postgres.sql`:
///
/// ```sql
/// CREATE TABLE "users" (
///     "id"            uuid         NOT NULL DEFAULT gen_random_uuid(),
///     "email"         varchar(255) NOT NULL,
///     "password_hash" text,
///     "jwt_secret"    text,
///     "username"      varchar(100),
///     "first_name"    varchar(255),
///     "last_name"     varchar(255),
///     "avatar_url"    text,
///     "is_active"     bool         NOT NULL DEFAULT true,
///     "is_verified"   bool         NOT NULL DEFAULT false,
///     "created_at"    timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
///     "updated_at"    timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
///     PRIMARY KEY ("id")
/// );
/// ```
#[derive(Debug, Clone)]
pub struct User {
    /// Primary key — `uuid`, generated by `gen_random_uuid()`.
    pub id: uuid::Uuid,

    /// Unique email address — `varchar(255) NOT NULL`.
    /// Enforced at DB level via `CREATE UNIQUE INDEX users_email`.
    pub email: String,

    /// Argon2 / bcrypt hash of the user's password — `text`, nullable.
    /// `None` for OAuth-only accounts that have no local password set.
    pub password_hash: Option<String>,

    /// Per-user HMAC secret used to sign and invalidate JWTs — `text`, nullable.
    /// Rotating this field instantly invalidates all existing tokens for the user.
    pub jwt_secret: Option<String>,

    /// Unique display handle — `varchar(100)`, nullable.
    /// Enforced at DB level via `CREATE UNIQUE INDEX users_username_key`.
    pub username: Option<String>,

    /// Given name — `varchar(255)`, nullable.
    pub first_name: Option<String>,

    /// Family name — `varchar(255)`, nullable.
    pub last_name: Option<String>,

    /// URL of the user's profile picture — `text`, nullable.
    pub avatar_url: Option<String>,

    /// Whether the account is allowed to authenticate — `bool NOT NULL DEFAULT true`.
    pub is_active: bool,

    /// Whether the user has confirmed their email address — `bool NOT NULL DEFAULT false`.
    pub is_verified: bool,

    /// Row creation timestamp — `timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP`.
    pub created_at: chrono::DateTime<chrono::Utc>,

    /// Last update timestamp — `timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP`.
    /// Should be refreshed on every `UPDATE`.
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

/// Ready-to-insert user data, produced by the service layer and consumed by
/// [`crate::interfaces::user_repo::UserRepo::create`].
///
/// Unlike [`RegisterRequest`], every sensitive field here is already processed:
/// `password_hash` holds the Argon2 output and `jwt_secret` is a freshly
/// generated random secret — the repository just writes them verbatim.
#[derive(Debug, Clone)]
pub struct NewUser {
    pub email: String,
    /// Argon2 hash of the plaintext password from [`RegisterRequest`].
    pub password_hash: String,
    /// Random per-user secret used to sign JWTs; generated by the service.
    pub jwt_secret: String,
    pub username: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
}

/// Inbound data required to register a new user.
///
/// Constructed by the caller (e.g. an HTTP handler) and passed to
/// [`crate::interfaces::auth::AuthService::register`].
///
/// The `password` field holds the **raw** plaintext password; the service
/// layer is responsible for hashing it before persistence.
#[derive(Debug, Clone)]
pub struct RegisterRequest {
    /// Must pass format validation and be unique across the `users` table.
    pub email: String,

    /// Plaintext password — will be hashed by the service before storage.
    pub password: String,

    /// Optional display handle — must be unique if provided.
    pub username: Option<String>,

    pub first_name: Option<String>,
    pub last_name: Option<String>,
}

/// Returned to the caller after a successful registration.
///
/// Intentionally omits sensitive fields (`password_hash`, `jwt_secret`).
#[derive(Debug, Clone)]
pub struct RegisterResponse {
    /// The newly created user's database UUID.
    pub user_id: uuid::Uuid,
    pub email: String,
    pub username: Option<String>,
}
